# Permalinks
permalink:           pretty

# Setup
title: 				 Random Thoughts, Hints and other Embedded madness
tagline:             Feeling adventurous?
url: 				 https://olivierschonken.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Olivier Schonken
  url:               https://olivierschonken.github.io
  email:             olivier.schonken@gmail.com
  github_username:  olivierschonken

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/olivierschonken/olivierschonken.github.io

# This is the list of pages to include in the header of the website.
pages_list:       
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
